<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSPedidoWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSPedidoWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSPedidoWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wspedido/">
    <import location="http://localhost:16373/1_Pedidos/WSPedido?WSDL" namespace="http://wspedido/"/>
    <plnk:partnerLinkType name="WSPedidoLinkType">
        <plnk:role name="WSPedidoRole" portType="ns:WSPedido"/>
    </plnk:partnerLinkType>
</definitions>
